version: "3.1"
volumes:
  grafana_data: {}
services:
  flask-server:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - 5000:5000
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
  grafana:
    build:
      context: .
      dockerfile: Dockerfile.grafana
    container_name: grafana-sales-analytics
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    ports:
      - 3000:3000
